#!/bin/bash
# Sometimes logging out and in (or triggering a hypr restart by updating waybar config) breaks environment variables for hyprland/XDG for processes running under tmux.
# To fix this we update the tmux server's global env, as well as any running zsh sessions.
# Taken from github.com/hyprwm/Hyprland/discussions/3098.
_envs=(
	# display
	WAYLAND_DISPLAY
	DISPLAY
	# xdg
	USERNAME
	XDG_BACKEND
	XDG_CURRENT_DESKTOP
	XDG_SESSION_TYPE
	XDG_SESSION_ID
	XDG_SESSION_CLASS
	XDG_SESSION_DESKTOP
	XDG_SEAT
	XDG_VTNR
	# hyprland
	HYPRLAND_CMD
	HYPRLAND_INSTANCE_SIGNATURE
	# sway
	SWAYSOCK
	# ssh
	SSH_AUTH_SOCK
)

dbus-update-activation-environment --systemd "${_envs[@]}"

for v in "${_envs[@]}"; do
	if [[ -n ${!v} ]]; then
		tmux setenv -g "$v" "${!v}"
	fi
done

NEW_INSTANCE=$HYPRLAND_INSTANCE_SIGNATURE

tmux list-panes -s -F "#{session_name}:#{window_index}.#{pane_index} #{pane_current_command}" | \
while read pane_process
do
	IFS=' ' read -ra pane_process <<< "$pane_process"
	if [[ "${pane_process[1]}" == "zsh" || "${pane_process[1]}" == "bash" ]]; then
		tmux send-keys -t ${pane_process[0]} C-c ";export HYPRLAND_INSTANCE_SIGNATURE=$NEW_INSTANCE" Enter
	fi
done
